### ISSUE TITLE
可能可以适配更多播放器的方法

### ISSUE THREAD

**Issue by sf467** [chiyuki0325/PlasmaAudaciousLyrics#10]
可不可以这样做，mpris 获取歌曲的名字或者歌曲文件的文件名，和播放进度
然后在本地的某个文件夹里搜索同名歌词文件并显示出来

**Comment by chiyuki0325** [comment]
@sf467 「某个文件夹」是指什么？

**Comment by sf467** [comment]
> @sf467 「某个文件夹」是指什么？

就是一个用于存放歌词 lrc 文件的文件夹，具体的位置可以由 lyrica 指定

**Comment by chiyuki0325** [comment]
@sf467 你提到的不支持的播放器是什么？我去看一下

**Comment by sf467** [comment]
> @sf467 你提到的不支持的播放器是什么？我去看一下

一种猜想啦，我现在用的播放器和 lyric 搭配得很完美
硬要说的话，kde connect 可能符合这个？
一种挺另类的播放方式，平能没别人这样做
就是手机播放本地歌曲，然后通过蓝牙把音频传输到电脑，之后就可以用 kde connect 在媒体中心显示歌曲的封面，可以用电脑的媒体键来控制播放进度
之所以用蓝牙传输到电脑，是因为耳机插在电脑上

**Comment by chiyuki0325** [comment]
在手机上放歌，然后特地去电脑上下 lrc 文件 ... 感觉没人会这样做的 ... 吧
并且即使本地找不到对应 lrc 文件，软件也会去网易云上搜，这样能匹配到 80% 以上的现行歌曲了（大概）
无论如何，如果你真的用这种方式听歌的话，那么欢迎 pr（逃

**Comment by sf467** [comment]
> 软件也会去网易云上搜，这样能匹配到 80% 以上的现行歌曲了（大概）

我一直是有意在避免用网易云的歌词源的，所以一直在使用 lyrica ，而不是别的可以显示歌词的挂件，原因就是网易云提供的歌词的时间轴还没我自己打的准（
> 无论如何，如果你真的用这种方式听歌的话，那么欢迎 pr（逃

这个我还是很想出一份力的，所以已经在学了（新建文件夹）

**Comment by chiyuki0325** [comment]
现在可以自己设置 lrc 文件夹路径

**Comment by sf467** [comment]
> 现在可以自己设置 lrc 文件夹路径

斩风千雪我爱你

**Comment by chiyuki0325** [comment]
@sf467 喵
